### ISSUE TITLE
Unexpected Identifier in bot.js (ALPHA BRANCH)

### ISSUE THREAD

**Issue by realjbtytm** [ImmunityNetwork/Drift#1]
The unexpected identifiers are jsfiles and props.

Those are causing an error before launching the bot, causing it to crash.

```
SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by realjbtytm** [comment]
Resolved with Commit 7fc769b
